/**
 * Generates the canonical Open Graph images for the Theseus homepage.
 *
 * Outputs (1200x630):
 *   - public/og/root.gif — animated, looping, cream hero card with the exact
 *     typewriter cycle from src/components/Pages/Home/Hero.tsx ("Verified." →
 *     "Autonomous." → "Sovereign." at 85 ms type / 40 ms delete / 1800 ms hold).
 *   - public/og/root.png — static frame 1 ("Verified."). Wired as
 *     twitter:image and as a secondary og:image fallback. Twitter and Telegram
 *     do not reliably render animated GIFs in link previews; the PNG ensures
 *     they always have something to display. Discord, LinkedIn, Slack render
 *     the GIF.
 *
 * Run when the brand line, headline copy, or visual treatment changes:
 *
 *   npm run gen:og
 *
 * Then commit the updated public/og/root.gif and public/og/root.png. These
 * files are not regenerated by the Next.js build; per-segment OGs at /docs,
 * /launch, /playground are still generated dynamically by Next.js via their
 * respective opengraph-image.tsx files.
 */

import { execFile } from "node:child_process";
import { mkdir, readFile, stat, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

import React from "react";
import satori, { type SatoriOptions } from "satori";
import { Resvg } from "@resvg/resvg-js";
import GIFEncoder from "gif-encoder-2";
import gifsicle from "gifsicle";
import sharp from "sharp";

void React;

const execFileAsync = promisify(execFile);

// Facebook explicitly recommends 1200x630, and gifsicle's lossy + interframe
// optimization keeps even full-size frames small enough to clear Telegram's
// undocumented animation threshold.
const WIDTH = 1200;
const HEIGHT = 630;

const ROTATING_WORDS = ["Verified.", "Autonomous.", "Sovereign."] as const;
const TYPE_MS = 85;
const DELETE_MS = 40;
const HOLD_MS = 1800;

const FONT_URLS = {
  serifRegular:
    "https://raw.githubusercontent.com/google/fonts/main/ofl/instrumentserif/InstrumentSerif-Regular.ttf",
  serifItalic:
    "https://raw.githubusercontent.com/google/fonts/main/ofl/instrumentserif/InstrumentSerif-Italic.ttf",
  sansRegular:
    "https://raw.githubusercontent.com/vercel/geist-font/main/packages/next/dist/fonts/geist-sans/Geist-Regular.ttf",
  sansSemiBold:
    "https://raw.githubusercontent.com/vercel/geist-font/main/packages/next/dist/fonts/geist-sans/Geist-SemiBold.ttf",
  monoRegular:
    "https://raw.githubusercontent.com/vercel/geist-font/main/packages/next/dist/fonts/geist-mono/GeistMono-Regular.ttf",
} as const;

async function fetchFont(url: string): Promise<ArrayBuffer> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Font fetch failed (${res.status}): ${url}`);
  return res.arrayBuffer();
}

const LOGO_RENDER_PX = 96;

/**
 * Renders src/assets/logo.svg as a pure black silhouette PNG (data URL).
 *
 * The website applies `filter: brightness(0)` in CSS to render the same
 * Theseus mark in solid black. Satori does not support CSS filters, so we
 * pre-render the silhouette here: rasterize the SVG with resvg, then zero
 * the RGB channels of every opaque pixel (preserving alpha).
 */
async function loadBlackLogoDataUrl(): Promise<string> {
  const svgPath = resolve(
    dirname(fileURLToPath(import.meta.url)),
    "..",
    "src",
    "assets",
    "logo.svg",
  );
  const svgBuffer = await readFile(svgPath);

  const rendered = new Resvg(svgBuffer, {
    fitTo: { mode: "width", value: LOGO_RENDER_PX },
  }).render();

  const { width, height, pixels } = rendered;
  const rgba = Buffer.from(pixels);
  for (let i = 0; i < rgba.length; i += 4) {
    if (rgba[i + 3] > 0) {
      rgba[i] = 0;
      rgba[i + 1] = 0;
      rgba[i + 2] = 0;
    }
  }

  const png = await sharp(rgba, {
    raw: { width, height, channels: 4 },
  })
    .png()
    .toBuffer();

  return `data:image/png;base64,${png.toString("base64")}`;
}

function frame(typed: string, logoSrc: string) {
  return (
    <div
      style={{
        width: "100%",
        height: "100%",
        background: "#ffffff",
        padding: 28,
        display: "flex",
        fontFamily: '"Geist"',
        color: "#0f172a",
      }}
    >
      <div
        style={{
          width: "100%",
          height: "100%",
          background: "#F1EAE1",
          borderRadius: 28,
          padding: "60px 80px",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          boxShadow: [
            "inset 0 1px 0 rgba(255,255,255,0.65)",
            "0 0 0 1px rgba(15,23,42,0.05)",
            "0 18px 40px -20px rgba(15,23,42,0.18)",
          ].join(", "),
        }}
      >
        <div style={{ display: "flex", flexDirection: "column", width: "100%" }}>
          <div
            style={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              paddingBottom: 10,
              fontSize: 22,
              fontWeight: 600,
              letterSpacing: "-0.01em",
              color: "#0f172a",
            }}
          >
            <div style={{ display: "flex", alignItems: "center", gap: 14 }}>
              <img
                src={logoSrc}
                width={36}
                height={36}
                alt=""
                style={{ display: "flex" }}
              />
              <span>Theseus Network</span>
            </div>
            <span
              style={{
                fontFamily: '"Geist Mono"',
                fontSize: 20,
                letterSpacing: 0,
              }}
            >
              00
            </span>
          </div>
          <div style={{ height: 1, background: "rgba(100,116,139,0.55)" }} />
        </div>

        <div
          style={{
            fontFamily: '"Instrument Serif"',
            fontSize: 124,
            letterSpacing: "-0.024em",
            color: "#0f172a",
            display: "flex",
            flexDirection: "column",
          }}
        >
          <div style={{ display: "flex", height: 130, alignItems: "flex-end" }}>
            <span style={{ lineHeight: 1 }}>Agents that are</span>
          </div>
          <div style={{ display: "flex", height: 130, alignItems: "flex-end" }}>
            <span style={{ fontStyle: "italic", lineHeight: 1 }}>{typed}</span>
            <span
              style={{
                display: "flex",
                width: 7,
                height: 100,
                marginLeft: 6,
                marginBottom: 14,
                background: "#0f172a",
              }}
            />
          </div>
        </div>

        <div
          style={{
            fontSize: 30,
            lineHeight: 1.4,
            color: "#475569",
            maxWidth: 820,
          }}
        >
          The open runtime where agents can act, live and persist.
        </div>
      </div>
    </div>
  );
}

type FrameSpec = { typed: string; delayMs: number };

/**
 * Build the (typed, delay) sequence that mirrors Hero.tsx's typewriter loop.
 *
 * The animation samples every Nth character during type/delete and multiplies
 * the per-frame delay so the perceived character cadence stays close to the
 * 85 ms / 40 ms hero. A larger STRIDE produces fewer frames and a smaller
 * GIF, at the cost of slightly chunkier per-character motion.
 *
 * Telegram silently refuses to animate `og:image` GIFs above an undocumented
 * threshold (empirically ~400 KB). STRIDE = 3 keeps us well under it without
 * visible degradation on the cream/charcoal art.
 */
const STRIDE = 3;

function buildSequence(): FrameSpec[] {
  const seq: FrameSpec[] = [];

  seq.push({ typed: ROTATING_WORDS[0], delayMs: HOLD_MS });

  for (let i = 0; i < ROTATING_WORDS.length; i++) {
    const word = ROTATING_WORDS[i];
    const next = ROTATING_WORDS[(i + 1) % ROTATING_WORDS.length];

    for (let n = word.length - STRIDE; n >= 0; n -= STRIDE) {
      seq.push({ typed: word.slice(0, n), delayMs: DELETE_MS * STRIDE });
    }
    if (word.length % STRIDE !== 0) {
      seq.push({ typed: "", delayMs: DELETE_MS * STRIDE });
    }
    for (let n = STRIDE; n < next.length; n += STRIDE) {
      seq.push({ typed: next.slice(0, n), delayMs: TYPE_MS * STRIDE });
    }
    seq.push({ typed: next, delayMs: TYPE_MS * STRIDE });
    if (i < ROTATING_WORDS.length - 1) {
      seq.push({ typed: next, delayMs: HOLD_MS });
    }
  }

  return seq;
}

async function renderFrame(
  typed: string,
  fonts: SatoriOptions["fonts"],
  logoSrc: string,
) {
  const svg = await satori(frame(typed, logoSrc), {
    width: WIDTH,
    height: HEIGHT,
    fonts,
  });
  return new Resvg(svg, { fitTo: { mode: "width", value: WIDTH } })
    .render()
    .pixels;
}

async function main() {
  process.stdout.write("Loading fonts and logo...\n");
  const [serifRegular, serifItalic, sansSemiBold, sansRegular, monoRegular, logoSrc] =
    await Promise.all([
      fetchFont(FONT_URLS.serifRegular),
      fetchFont(FONT_URLS.serifItalic),
      fetchFont(FONT_URLS.sansSemiBold),
      fetchFont(FONT_URLS.sansRegular),
      fetchFont(FONT_URLS.monoRegular),
      loadBlackLogoDataUrl(),
    ]);

  const fonts: SatoriOptions["fonts"] = [
    { name: "Geist", data: sansRegular, weight: 400, style: "normal" },
    { name: "Geist", data: sansSemiBold, weight: 600, style: "normal" },
    { name: "Instrument Serif", data: serifRegular, weight: 400, style: "normal" },
    { name: "Instrument Serif", data: serifItalic, weight: 400, style: "italic" },
    { name: "Geist Mono", data: monoRegular, weight: 400, style: "normal" },
  ];

  const sequence = buildSequence();
  process.stdout.write(`Rendering ${sequence.length} frames...\n`);

  const cache = new Map<string, Uint8Array>();
  const rendered: Uint8Array[] = [];
  for (let i = 0; i < sequence.length; i++) {
    const { typed } = sequence[i];
    let pixels = cache.get(typed);
    if (!pixels) {
      pixels = await renderFrame(typed, fonts, logoSrc);
      cache.set(typed, pixels);
    }
    rendered.push(pixels);
    if ((i + 1) % 10 === 0 || i === sequence.length - 1) {
      process.stdout.write(`  ${i + 1}/${sequence.length}\n`);
    }
  }

  process.stdout.write("Encoding GIF...\n");
  const encoder = new GIFEncoder(WIDTH, HEIGHT, "neuquant", true, sequence.length);
  encoder.setRepeat(0);
  // neuquant sample interval; higher = smaller palette, smaller file. 30 is
  // the most aggressive setting and stays imperceptible on the flat
  // cream/charcoal palette (only ~6 distinct colors in play).
  encoder.setQuality(30);
  encoder.start();
  for (let i = 0; i < sequence.length; i++) {
    encoder.setDelay(sequence[i].delayMs);
    encoder.addFrame(rendered[i]);
  }
  encoder.finish();

  const buffer: Buffer = encoder.out.getData();
  const ogDir = resolve(
    dirname(fileURLToPath(import.meta.url)),
    "..",
    "public",
    "og",
  );
  await mkdir(ogDir, { recursive: true });

  const gifPath = resolve(ogDir, "root.gif");
  await writeFile(gifPath, buffer);
  process.stdout.write(
    `Encoded ${gifPath} (${(buffer.length / 1024).toFixed(1)} KB, ${sequence.length} frames)\n`,
  );

  // Post-process with gifsicle. -O3 enables full inter-frame optimization,
  // --lossy=80 trades imperceptible color-quantization noise for ~40-50%
  // size reduction on flat-color art. Telegram refuses to animate `og:image`
  // GIFs above an undocumented threshold (empirically ~400 KB), so we need
  // every byte of compression we can get.
  process.stdout.write("Optimizing GIF with gifsicle...\n");
  await execFileAsync(gifsicle, [
    "-O3",
    "--lossy=80",
    "--no-warnings",
    "-o",
    gifPath,
    gifPath,
  ]);
  const optimizedSize = (await stat(gifPath)).size;
  process.stdout.write(
    `Optimized ${gifPath} (${(optimizedSize / 1024).toFixed(1)} KB)\n`,
  );

  process.stdout.write("Encoding static PNG fallback (frame 1)...\n");
  const firstFrame = rendered[0];
  const pngBuffer = await sharp(Buffer.from(firstFrame), {
    raw: { width: WIDTH, height: HEIGHT, channels: 4 },
  })
    .png({ compressionLevel: 9 })
    .toBuffer();
  const pngPath = resolve(ogDir, "root.png");
  await writeFile(pngPath, pngBuffer);
  process.stdout.write(
    `Wrote ${pngPath} (${(pngBuffer.length / 1024).toFixed(1)} KB)\n`,
  );
}

main().catch((err) => {
  process.stderr.write(`gen-og-animated failed: ${err?.stack ?? err}\n`);
  process.exit(1);
});
